app:
  build: ./
  volumes:
    - ./:/app
  ports:
    - 8080:8080
  environment:
    - NODE_ENV=development
    - PORT=8080
  command:
    sh -c 'find /var/lib/mysql -type f -exec touch {} \;&& /etc/init.d/mysql start / && mysql -u root -e "CREATE DATABASE tp_db;USE tp_db;CREATE TABLE indexCpt (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,cpt INT )" && node index.js'